# Generated by cucumber-sinatra. (2015-04-06 10:27:10 +0100)

ENV['RACK_ENV'] = 'test'

require_relative '../../app/server'

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = BookmarkManager

class BookmarkManagerWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  BookmarkManagerWorld.new
end
